apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsa-fe
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fsa-fe
  template:
    metadata:
      labels:
        app: fsa-fe
    spec:
      containers:
        - name: fsa-fe
          image: fsa2024rsvistularegistry.azurecr.io/fsa-frontend:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 250m
              memory: 300Mi
            requests:
              cpu: 150m
              memory: 201Mi
          ports:
            - name: http
              containerPort: 80
