apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
data:
  db_username: ZnNhYWRtaW4=
  db_password: UEBzc3dvcmQxMjM0NQ==
  db_url: ZnNhMjAyNC1yc3Zpc3R1bGEtcHNxbC5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb20=

---

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: app
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
data:
  kc_username: YWRtaW4=
  kc_password: YWRtaW4=

---

apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin
  namespace: infra
  annotations:
    kubernetes.io/service-account.name: default
type: Opaque
data:
  jenkins-admin-user: Um9zdHlzbGF2
  jenkins-admin-password: YWRtaW4=