apiVersion: v1
kind: Secret
metadata:
  name: acr-credentials
  namespace: infra
  labels:
     "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "Credentials for Azure Container Registry"
    kubernetes.io/service-account.name: jenkins
type: Opaque
data:
  username: ZnNhMjAyNHJzdmlzdHVsYXJlZ2lzdHJ5
  password: T2JxUVFveHFnSXNLbFh2ZVRTaWRBZmEyN0JmcG5Nc1o5VUdTS290NlNqK0FDUkRVY25aTw==

---

apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: infra
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "Credentials for GitHub"
    kubernetes.io/service-account.name: jenkins
type: Opaque
data:
  username: Um9zdFNW
  password: Z2hwX3kxQjNDUDFHdEZpWlpqcGdubmhCeWhiWE01Z0hUcDFiU2NNbg==
